Repository autogoal/autogoal, pull requests merged in 2020-11, with the labels that each got.

#47 Addition of a beginning of the stacking generalization program
  autogoal/contrib/ensemble/__init__.py
  autogoal/contrib/ensemble/_stacking.py
  tests/contrib/test_ensemble.py
Labels: enhancement, hacktoberfest2020

#50 Added build pipeline tests
  tests/core/test_build_pipeline.py
Labels: enhancement

#51 Issue dataset storage
  autogoal/datasets/__init__.py
  autogoal/datasets/abalone.py
  autogoal/datasets/gisette.py
  autogoal/datasets/meddocan.py
  autogoal/datasets/shuttle.py
  autogoal/datasets/yeast.py
Labels: enhancement, wip
