Repository autogoal/autogoal, pull requests merged in 2020-10, with the labels that each got.

#17 Refactor contrib (second try)
  .github/workflows/main.yml
  Readme.md
  autogoal/ml/__init__.py
  autogoal/ml/_automl.py
  autogoal/ml/_metalearning.py
  dockerfile
  makefile
  poetry.lock
  pyproject.toml
  tests/basic.dockerfile
Labels: enhancement, hacktoberfest2020

#38 Enrich documentation
  docs/examples/comparing_search_strategies.md
  docs/examples/sklearn_simple_grammar.md
  docs/examples/solving_haha_2019.md
  docs/examples/solving_meddocan_2019.md
  docs/examples/solving_uci_datasets.md
  docs/make_docs.py
Labels: hacktoberfest2020

#42 Fix moview reviews example
  autogoal/datasets/movie_reviews.py
  docs/examples/sklearn_simple_grammar.py
Labels: hacktoberfest-accepted, hacktoberfest2020
